spring:
  application:
    name: xxl-arms
#
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/xxl_arms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: root
#    password: xxl666
  
  # MyBatis-Flex配置
  mybatis-flex:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启SQL日志
    sql-log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 8080

logging:
  level:
    com.xxl.prometheus: DEBUG

# 监控指标
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
#  metrics:
#    export:
#      prometheus:
#        enabled: true
  endpoint:
    health:
      show-details: always
