spring:
  application:
    name: alibaba-ai-demo
  ai:
    dashscope:
      api-key: sk-e9add5896dd84ba49d0f142dab6383d9 # API-KEY
      chat:
        options:
          model: deepseek-r1   # 模型名称
    mcp:
      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
        stdio:
         servers-configuration: classpath:mcp-servers.json
  # redis 配置
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

#  功能扩展
extend:
  # 自定义 Advisor
  advisor:
  # 对话记忆持久化
  memory: